name: nesemu2 CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: linux build
      run: |
        sudo apt install wget git build-essential libsdl2-dev
        make -j$(getconf _NPROCESSORS_ONLN)

  windows:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          gcc
          git
          make
          zip
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
    - uses: actions/checkout@v4
    - name: windows build
      shell: msys2 {0}
      run: make
